server:
  port: 9443

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: warehouse-super-secret-key
  expiration: 86400000

logging:
  file:
    name: C:/Users/66945/Desktop/Sprig Boot/logs/warehouse-project/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    com.warehouse: DEBUG